# Generated by Django 5.2.4 on 2025-08-28 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('assessment_summary', 'Assessment Summary'), ('department_comparison', 'Department Comparison'), ('trend_analysis', 'Trend Analysis'), ('gap_analysis', 'Gap Analysis'), ('improvement_roadmap', 'Improvement Roadmap'), ('executive_summary', 'Executive Summary')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('assessment_summary', 'Assessment Summary'), ('department_comparison', 'Department Comparison'), ('trend_analysis', 'Trend Analysis'), ('gap_analysis', 'Gap Analysis'), ('improvement_roadmap', 'Improvement Roadmap'), ('executive_summary', 'Executive Summary')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html', 'docx', 'xlsx'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('assessment_summary', 'Assessment Summary'), ('department_comparison', 'Department Comparison'), ('trend_analysis', 'Trend Analysis'), ('gap_analysis', 'Gap Analysis'), ('improvement_roadmap', 'Improvement Roadmap'), ('executive_summary', 'Executive Summary')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word'), ('html', 'HTML')], max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='generated_reports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('downloaded', 'Downloaded')], default='processing', max_length=20)),
                ('generation_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assessments.assessment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.department')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='generated_r_report__f802cc_idx'), models.Index(fields=['requested_by', 'generated_at'], name='generated_r_request_a2943a_idx')],
            },
        ),
    ]
