# Generated by Django 5.2.4 on 2025-08-28 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('assessment_period', models.CharField(default='Q1 2025', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_template', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.organization')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('establishing_bcms', 'Establishing a BCMS'), ('embracing_bc', 'Embracing Business Continuity'), ('analysis', 'Analysis'), ('solution_design', 'Solution Design'), ('enabling_solutions', 'Enabling Solutions'), ('validation', 'Validation')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_focus_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'focus_areas',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('guidance_notes', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.focusarea')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['focus_area__order_index', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity_score', models.PositiveIntegerField(blank=True, choices=[(0, '0 - Not Started (0%)'), (1, '1 - Initial (1-39%)'), (2, '2 - Developing/Repeatable (40-59%)'), (3, '3 - Defined (60-79%)'), (4, '4 - Managed (80-99%)'), (5, '5 - Optimized (100%)')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_evidence', models.BooleanField(default=False)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.question')),
            ],
            options={
                'db_table': 'assessment_responses',
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status', 'due_date'], name='assessments_status_c9895d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['organization', 'department'], name='assessments_organiz_a8a28f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('focus_area', 'code')},
        ),
        migrations.AddIndex(
            model_name='assessmentresponse',
            index=models.Index(fields=['assessment', 'question'], name='assessment__assessm_cdb657_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresponse',
            index=models.Index(fields=['maturity_score'], name='assessment__maturit_3a0222_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresponse',
            unique_together={('assessment', 'question')},
        ),
    ]
