# Generated by Django 5.2.4 on 2025-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_question_options_component_focusarea_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
